'use strict';
// Prototype data lives only in memory for this visit. No account, network request, or storage.
const $ = id => document.getElementById(id);
const companions = [
  {name:'Kya',role:'Support Dog',icon:'🐶'}, {name:'Luna',role:'Cat',icon:'🐱'},
  {name:'Buddy',role:'Dog',icon:'🐕'}, {name:'Audrey',role:'Helper',icon:'👩'},
  {name:'Ethan',role:'Encourager',icon:'🧑'}, {name:'Nova',role:'Dreamer',icon:'✨'},
  {name:'Remi',role:'Brave One',icon:'🦊'}, {name:'Ziggy',role:'Explorer',icon:'🦓'}
];
const feelings = [{name:'Happy',icon:'😊'},{name:'Okay',icon:'😐'},{name:'Sad',icon:'😢'},{name:'Angry',icon:'😡'},{name:'Worried',icon:'😟'}];
const state = {companion:0,name:'Kya',personality:'Calm & gentle',voiceURI:'',speed:1,feeling:null,checkins:[],calms:[],practice:[],recognition:null,session:null,step:0,game:null};
function say(message){if(!('speechSynthesis' in window))return;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(message);utterance.rate=state.speed;const chosen=speechSynthesis.getVoices().find(v=>v.voiceURI===state.voiceURI);if(chosen)utterance.voice=chosen;utterance.onstart=()=>setStatus('Talking');utterance.onend=()=>setStatus('Ready');utterance.onerror=()=>setStatus('Ready');speechSynthesis.speak(utterance)}
function setStatus(status){$('status').textContent='● '+(status==='Ready'?'Ready to talk':status==='Listening'?'Listening…':'Talking…');$('character').classList.toggle('listening',status==='Listening');$('character').classList.toggle('talking',status==='Talking')}
function respond(message,spoken=true){$('bubble').textContent=message;addChat(state.name,message,false);if(spoken)say(message)}
function addChat(who,message,mine){const line=document.createElement('div');line.className='chatmsg'+(mine?' mine':'');const label=document.createElement('span');label.textContent=who;line.append(label,document.createTextNode(message));$('chatLog').append(line);$('chatLog').scrollTop=$('chatLog').scrollHeight}
function replyFor(message){const m=message.toLowerCase();if(/(hurt myself|kill myself|suicide|self harm|not safe)/.test(m))return "I'm glad you told me. Please tell a trusted adult with you right now. If someone is in immediate danger, call local emergency services.";if(/(sad|bad day|cry|upset|lonely)/.test(m))return "I'm sorry today feels hard. Would you like to tell me what happened, or take a quiet breath with me?";if(/(scared|worried|anxious|nervous)/.test(m))return "That sounds worrying. Let's slow down together. What's one thing that might help you feel safer right now?";if(/(angry|mad|frustrat)/.test(m))return "It makes sense to need a pause when you're frustrated. Want to try breathing or tell me what happened?";if(/(homework|school|math|read)/.test(m))return "We can take it one step at a time. What is the first part you understand?";if(/(happy|good|excited|great)/.test(m))return "I'm happy to hear that! What was the best part?";return state.personality==='Silly & fun'?"I'm here with my listening ears! Tell me a little more. 🐾":"I'm listening. Would you like to tell me more about that?"}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
function renderCompanions(){const box=$('companions');box.replaceChildren();companions.forEach((c,i)=>{const button=document.createElement('button');button.className='companion'+(state.companion===i?' active':'');button.setAttribute('aria-pressed',String(state.companion===i));const icon=document.createElement('span');icon.className='avatar';icon.textContent=c.icon;const title=document.createElement('strong');title.textContent=c.name;const role=document.createElement('small');role.textContent=c.role;button.append(icon,title,role);button.onclick=()=>{stopAll();state.companion=i;state.name=c.name;updateCompanion();renderCompanions()};box.append(button)})}
function updateCompanion(){$('companionTitle').textContent=state.name;$('micBtn').textContent='🎙 Talk to '+state.name;$('nameSetting').value=state.name;$('character').hidden=state.companion!==0;$('companionIcon').hidden=state.companion===0;$('companionIcon').textContent=companions[state.companion].icon;$('bubble').textContent=`Hi, I’m ${state.name}. Want to tell me about your day?`}
renderCompanions();updateCompanion();
$('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatInput').value.trim();if(!text)return;addChat('You',text,true);$('chatInput').value='';respond(replyFor(text))};
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
$('micBtn').onclick=()=>{if(!Recognition){$('bubble').textContent='Voice listening is unavailable in this browser. You can type to me instead.';return}stopAll();const rec=new Recognition();state.recognition=rec;rec.lang=document.documentElement.lang||'en-US';rec.interimResults=false;rec.onstart=()=>setStatus('Listening');rec.onresult=e=>{const heard=e.results[0][0].transcript;addChat('You',heard,true);respond(replyFor(heard))};rec.onerror=e=>{$('bubble').textContent=e.error==='not-allowed'?'Please allow microphone access, or type your message.':'I couldn’t hear that. Please try again or type your message.';setStatus('Ready')};rec.onend=()=>{if($('status').textContent.includes('Listening'))setStatus('Ready');state.recognition=null};try{rec.start()}catch{setStatus('Ready')}};
function stopAll(){state.recognition?.abort();state.recognition=null;if('speechSynthesis' in window)speechSynthesis.cancel();setStatus('Ready')}$('stopBtn').onclick=stopAll;
function voices(){const select=$('voiceSetting');const old=state.voiceURI;select.replaceChildren(new Option('Device default',''));if('speechSynthesis' in window)speechSynthesis.getVoices().forEach(v=>select.add(new Option(`${v.name} (${v.lang})`,v.voiceURI)));select.value=old;if(select.selectedIndex<0)select.value=''}if('speechSynthesis' in window){voices();speechSynthesis.onvoiceschanged=voices}
$('settingsBtn').onclick=()=>{$('nameSetting').value=state.name;$('settings').showModal()};$('speedSetting').oninput=()=>{$('speedValue').textContent=Number($('speedSetting').value).toFixed(1)+'×'};$('previewVoice').onclick=()=>{state.voiceURI=$('voiceSetting').value;state.speed=Number($('speedSetting').value);say(`Hello! I'm ${state.name}. I'm happy to be here with you.`)};$('applySettings').onclick=()=>{state.name=$('nameSetting').value.trim()||companions[state.companion].name;state.voiceURI=$('voiceSetting').value;state.speed=Number($('speedSetting').value);state.personality=$('personalitySetting').value;document.body.dataset.background=$('backgroundSetting').value;updateCompanion()};
const choices=$('feelingChoices');feelings.forEach(f=>{const b=document.createElement('button');b.textContent=`${f.icon} ${f.name}`;b.onclick=()=>{state.feeling=f.name;choices.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b))};choices.append(b)});$('intensity').oninput=()=>{$('intensityValue').textContent=$('intensity').value+' / 5'};$('saveFeeling').onclick=()=>{if(!state.feeling){$('feelingMessage').textContent='Choose a feeling first.';return}state.checkins.push({feeling:state.feeling,intensity:Number($('intensity').value),happened:$('happened').value.trim(),helped:$('helped').value.trim()});$('feelingMessage').textContent='Check-in saved for this visit. Thank you for sharing.';$('happened').value='';$('helped').value=''};
const calmSteps={breathe:{title:'Breathe With Me',steps:['Breathe in slowly for four counts.','Breathe out slowly for four counts.','Take another gentle breath. Notice your feet on the floor.']},ground:{title:'5-4-3-2-1 Grounding',steps:['Name five things you can see.','Name four things you can feel.','Name three things you can hear.','Name two things you can smell.','Name one thing you can taste, or imagine a favorite taste.']},quiet:{title:'Quiet Time',steps:['Find a comfortable spot and relax your shoulders.','Notice your breath. There is nothing to get right.','Stay here as long as you like. You can ask a trusted person to sit with you.']}};
function calmStep(){const session=calmSteps[state.session];$('calmStep').textContent=session.steps[state.step];$('nextCalm').textContent=state.step===session.steps.length-1?'Finish steps':'Next step';say(session.steps[state.step])}
document.querySelectorAll('[data-calm]').forEach(b=>b.onclick=()=>{state.session=b.dataset.calm;state.step=0;$('calmSession').hidden=false;$('calmTitle').textContent=calmSteps[state.session].title;$('breathOrb').hidden=state.session!=='breathe';$('calmOutcome').hidden=true;$('nextCalm').hidden=false;calmStep()});$('nextCalm').onclick=()=>{if(state.step<calmSteps[state.session].steps.length-1){state.step++;calmStep()}else finishCalm()};function finishCalm(){stopAll();$('calmStep').textContent='You took a moment for yourself. How do you feel now?';$('calmOutcome').hidden=false;$('nextCalm').hidden=true}$('endCalm').onclick=finishCalm;document.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=()=>{state.calms.push({activity:calmSteps[state.session].title,outcome:b.dataset.outcome});$('calmStep').textContent='Thank you for checking in with yourself.';$('calmOutcome').hidden=true});
const games={word:{title:'Word Adventure',prompt:'Which word rhymes with cat?',choices:['Hat','Sun','Tree'],answer:0,skill:'Reading and phonics'},number:{title:'Number Quest',prompt:'What is 4 + 3?',choices:['6','7','8'],answer:1,skill:'Math'},memory:{title:'Memory Challenge',prompt:'Remember this order: star, moon, sun. What comes second?',choices:['Star','Moon','Sun'],answer:1,skill:'Memory and focus'},sequence:{title:'Sequencing',prompt:'What comes next: 2, 4, 6, …?',choices:['7','8','10'],answer:1,skill:'Sequencing'},pattern:{title:'Pattern Detective',prompt:'What comes next: 🔴 🔵 🔴 🔵 …?',choices:['🔴','🔵','🟡'],answer:0,skill:'Patterns'},spelling:{title:'Spelling',prompt:'Which one spells the animal correctly?',choices:['Dogg','Dog','Dgo'],answer:1,skill:'Spelling'}};
function openGame(key){state.game=key;const g=games[key];$('gameArea').hidden=false;$('gameTitle').textContent=g.title;$('gamePrompt').textContent=g.prompt;$('gameFeedback').textContent='';$('anotherGame').hidden=true;const box=$('gameChoices');box.replaceChildren();g.choices.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c;b.onclick=()=>{const correct=i===g.answer;state.practice.push({skill:g.skill,correct});$('gameFeedback').textContent=correct?'Nice work! ⭐':'Good try. The answer is '+g.choices[g.answer]+'.';box.querySelectorAll('button').forEach(x=>x.disabled=true);$('anotherGame').hidden=false};box.append(b)});$('gameArea').scrollIntoView({behavior:'smooth',block:'nearest'})}document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$('anotherGame').onclick=()=>openGame(state.game);
const extras={read:{title:'Read With Me',prompt:'Maya planted a tiny seed. Each morning she gave it water. Soon a green sprout appeared. What did Maya give the seed?',choices:['Water','A book','A hat'],answer:0,skill:'Reading comprehension'},homework:{title:'Homework Helper',prompt:'Let’s break it down: What is the question asking? What do you already know? What is one small first step you can try?'},focus:{title:'Memory & Focus',prompt:'Look around and find three things that are blue. Take your time.'}};
document.querySelectorAll('[data-extra]').forEach(b=>b.onclick=()=>{const key=b.dataset.extra;if(key==='strengths'){const strengths=state.practice.filter(x=>x.correct).reduce((a,x)=>(a[x.skill]=(a[x.skill]||0)+1,a),{});$('gameTitle').textContent='My Strengths';$('gamePrompt').textContent=Object.keys(strengths).length?Object.entries(strengths).map(([k,v])=>`${k}: ${v} successful practice moment${v===1?'':'s'}`).join(' • '):'Try a learning game. Your practice moments will appear here.';$('gameChoices').replaceChildren();$('gameFeedback').textContent='';$('anotherGame').hidden=true;$('gameArea').hidden=false;return}const x=extras[key];$('gameArea').hidden=false;$('gameTitle').textContent=x.title;$('gamePrompt').textContent=x.prompt;$('gameFeedback').textContent='';$('anotherGame').hidden=true;$('gameChoices').replaceChildren();if(x.choices){x.choices.forEach((label,i)=>{const button=document.createElement('button');button.textContent=label;button.onclick=()=>{const correct=i===x.answer;state.practice.push({skill:x.skill,correct});$('gameFeedback').textContent=correct?'Yes! Nice reading. ⭐':'Try reading the story once more.';$('gameChoices').querySelectorAll('button').forEach(v=>v.disabled=true)};$('gameChoices').append(button)})}});
$('saveJournal').onclick=()=>{$('journalMessage').textContent=$('journalText').value.trim()?'Kept on this page for this visit. It will disappear when you leave or refresh.':'Write something first, if you’d like.'};
function reportCard(title,body){const card=document.createElement('div');card.className='report-card';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=body;card.append(h,p);$('reportBody').append(card)}
$('openReport').onclick=()=>{$('caregiverGate').hidden=true;$('report').hidden=false;$('reportIntro').textContent='Kya noticed these practice and check-in moments during this visit. This summary is available only until this page is closed or refreshed.';$('reportBody').replaceChildren();const fc=state.checkins.reduce((a,x)=>(a[x.feeling]=(a[x.feeling]||0)+1,a),{});reportCard('Feelings check-ins',Object.keys(fc).length?Object.entries(fc).map(([k,v])=>`${k}: ${v}`).join(' • '):'No check-ins yet.');const skills=state.practice.reduce((a,x)=>{a[x.skill]??={attempts:0,successes:0};a[x.skill].attempts++;if(x.correct)a[x.skill].successes++;return a},{});reportCard('Learning practice',Object.keys(skills).length?Object.entries(skills).map(([k,v])=>`${k}: ${v.successes} of ${v.attempts} practice answers correct`).join(' • '):'No learning activities yet.');reportCard('Strengths and progress',Object.keys(skills).length?Object.entries(skills).filter(([,v])=>v.successes).map(([k,v])=>`${k}: ${v.successes} successful moment${v.successes===1?'':'s'}`).join(' • ')||'More practice will show strengths here.':'More practice will show strengths here.');reportCard('Calming activities',state.calms.length?state.calms.map(x=>`${x.activity} (${x.outcome.toLowerCase()} afterward)`).join(' • '):'No completed calming activities yet.');reportCard('Observation','These are simple activity observations from one visit. They do not identify or diagnose a condition.')};$('printReport').onclick=()=>window.print();
